# Generated by Django 5.1.1 on 2024-10-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
