services:
  web:
    build:
      context: devtool_system/
    ports:
      - "9090:8000"  # Exposing internal port 8000 for web container
    command: [ "sh", "./start.sh" ]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Mapping port 80 of the host to port 80 of the nginx container
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map your custom nginx configuration file

volumes:
  postgres_data:
