services:
  frontend:
    build: ./frontend  # Path to the frontend Dockerfile (Node.js)
    ports:
      - "8083:3000"    # Exposing port for frontend
    volumes:
      - ./frontend:/app  # Mounting local code for development

  backend:
    build: ./backend   # Path to the backend Dockerfile (PHP)
    ports:
      - "8000:8000"    # Exposing port for backend
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Ab123456*
      - DATABASE_NAME=app_db
      - NODEJS_HOST=frontend  # To allow PHP to communicate with Node.js
      - NODEJS_PORT=3000
      - APACHE_SERVER_NAME=backend
    volumes:
      - ./backend:/var/www/html  # Mounting PHP files

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ab123456*
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"  # Exposing PostgreSQL port
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistent data storage
      - ./db:/docker-entrypoint-initdb.d/  # Mount your SQL dump

volumes:
  db_data: